// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFiAZG1ctqSzQo3jAy4qQU0v_3MwfGZY',
    appId: '1:1076873568172:web:563b643ed2faa6961b6409',
    messagingSenderId: '1076873568172',
    projectId: 'database-tugas-akhir-inventory',
    authDomain: 'database-tugas-akhir-inventory.firebaseapp.com',
    storageBucket: 'database-tugas-akhir-inventory.firebasestorage.app',
    measurementId: 'G-RMT182DGRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdIpEaQ9x3CxD4utgAfGU041UbcKI7Eo',
    appId: '1:1076873568172:android:c7b2e4e05a1a64a01b6409',
    messagingSenderId: '1076873568172',
    projectId: 'database-tugas-akhir-inventory',
    storageBucket: 'database-tugas-akhir-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlTE5g68lsEqWrF_zKvBjhOfcfH0Elv9o',
    appId: '1:1076873568172:ios:6fe2e1d9cbab7ea61b6409',
    messagingSenderId: '1076873568172',
    projectId: 'database-tugas-akhir-inventory',
    storageBucket: 'database-tugas-akhir-inventory.firebasestorage.app',
    iosBundleId: 'com.nicholaswijaya.inventoryAppRevised',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlTE5g68lsEqWrF_zKvBjhOfcfH0Elv9o',
    appId: '1:1076873568172:ios:6fe2e1d9cbab7ea61b6409',
    messagingSenderId: '1076873568172',
    projectId: 'database-tugas-akhir-inventory',
    storageBucket: 'database-tugas-akhir-inventory.firebasestorage.app',
    iosBundleId: 'com.nicholaswijaya.inventoryAppRevised',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZFiAZG1ctqSzQo3jAy4qQU0v_3MwfGZY',
    appId: '1:1076873568172:web:c3e8cbdf050998d01b6409',
    messagingSenderId: '1076873568172',
    projectId: 'database-tugas-akhir-inventory',
    authDomain: 'database-tugas-akhir-inventory.firebaseapp.com',
    storageBucket: 'database-tugas-akhir-inventory.firebasestorage.app',
    measurementId: 'G-0FVZ9TH809',
  );
}
